import useWindowSize from "@/utils/useWindowSize";
import Head from "next/head";
import homeStyles from "../styles/Home.module.css";

function SmallScreen() {
  return <h1>amll</h1>;
}

function LargeScreen() {
  return <h1>Large</h1>;
}

export default function Home() {
  const { width } = useWindowSize();

  let body = <p style={{ marginTop: "80px" }}>Loading...</p>;
  if (width < 768) {
    body = <SmallScreen />;
  } else if (width >= 768) {
    body = <LargeScreen />;
  }

  return (
    <>
      <Head>
        <title>My Still Untitled Music Project</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {<div className={homeStyles.wrapper}>{body}</div>}
    </>
  );
}
